"""Write configs/regime/*.yaml, the v1.1 regime cells for the GPU runs (group G5).

    python -m scripts.make_regime_configs                      # write the configs
    python -m scripts.make_regime_configs --realistic-k k050   # gate D3 fired
    python -m scripts.make_regime_configs --check              # exit 1 if files drift
    python -m scripts.make_regime_configs --dry-run            # 2 CPU steps per run

Every file copies the shared settings and the pinn/lstm blocks of
configs/base.yaml and sets the fixed v1.1 protocol (full profile, 20000 steps,
total-derivative residual, 4-sample trailing RAS filter). Cell notation:
k<alpha x 100> kinetics, ie/ic exact or daily-composite influent, a0/as/al1
anchor. Seeds are not in the files: ``run_all --seed k`` writes
``results/v11/pinn/<cell>_seed<k>``.

Three files need group G4 outputs and are skipped, with a message, until they
exist: the two ``*_theta`` files read ``trainable_kinetics`` from
kinetic_subset.json ({"names": [...]}), and ``k100_ie_a0_sensors`` reads
sensor_confirmation.json ({"drop": <target channel>, "add": <candidate channel>}).
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.asm1.vault_loader import vault
from src.data.sensors import CANDIDATE_CHANNELS
from src.models.losses import kinetic_parameter_names
from src.train.run import TARGET_CHANNELS

BASE_CONFIG = Path("configs/base.yaml")
OUT_DIR = Path("configs/regime")
KINETIC_SUBSET = Path("results/v11/analysis/kinetic_subset.json")
SENSOR_CONFIRMATION = Path("results/v11/analysis/sensor_confirmation.json")
PINN_ROOT = "results/v11/pinn"
ANCHOR_ROOT = "results/v11/anchors"
DATA_DIRS = {"k000": "results/raw", "k050": "results/raw_k050", "k100": "results/raw_k100"}
REALISTIC_CHOICES = ("k100", "k050")
SIGMA = 0.10
HEADER = "# Generated by scripts/make_regime_configs.py - edit the generator, not this file."
V11_SETTINGS: dict[str, Any] = {
    "profile": "full",
    "steps_full": 20000,
    "device": "cuda",
    "dtype": "float32",
    "total_derivative": True,
    "ras_filter_window": 4,
}


@dataclass(frozen=True)
class Cell:
    stem: str
    cell: str
    k: str
    models: tuple[str, ...]
    anchor: str | None
    influent_mode: str
    purpose: str
    noise_levels: tuple[float, ...] = (SIGMA,)
    needs: str | None = None


def cells(realistic_k: str = "k100") -> list[Cell]:
    if realistic_k not in REALISTIC_CHOICES:
        raise ValueError("realistic_k must be one of %s, got %r" % (REALISTIC_CHOICES, realistic_k))
    k = realistic_k
    return [
        Cell("k000_ie_a0", "k000_ie_a0", "k000", ("cl_pinn", "pinn"), None, "exact",
             "E4: correct kinetics, exact influent, truth Z(0) (A0); H1 and H7"),
        Cell("k000_ic_a0", "k000_ic_a0", "k000", ("cl_pinn",), None, "composite",
             "E4: correct kinetics, daily composite influent, truth Z(0) (A0); H5"),
        Cell("k050_ie_a0", "k050_ie_a0", "k050", ("cl_pinn",), "A0", "exact",
             "E5: kinetic mismatch alpha 0.5, exact influent, oracle anchor"),
        Cell("k100_ie_a0", "k100_ie_a0", "k100", ("cl_pinn",), "A0", "exact",
             "E5: kinetic mismatch alpha 1 (BSM1 15 C set), exact influent, oracle anchor"),
        Cell("%s_ic_a0" % k, "%s_ic_a0" % k, k, ("cl_pinn",), "A0", "composite",
             "E6: realistic cell, oracle anchor"),
        Cell("%s_ic_as" % k, "%s_ic_as" % k, k, ("cl_pinn",), "As", "composite",
             "E6: realistic cell, nominal steady-state anchor; sigma 0.05 and 0.15 run "
             "with seeds 0 and 1 only", noise_levels=(0.05, 0.10, 0.15)),
        Cell("%s_ic_al1" % k, "%s_ic_al1" % k, k, ("cl_pinn",), "Al1", "composite",
             "E6: realistic cell, anchor updated with the routine laboratory panel; H4"),
        Cell("%s_ic_as_lstm" % k, "%s_ic_as" % k, k, ("lstm",), "As", "composite",
             "E6: model-free floor in the realistic cell"),
        Cell("k100_ie_a0_theta", "k100_ie_a0", "k100", ("cl_pinn_theta",), "A0", "exact",
             "E7: joint kinetic estimation under mismatch; H3", needs="kinetics"),
        Cell("k000_ie_a0_theta", "k000_ie_a0", "k000", ("cl_pinn_theta",), None, "exact",
             "E7: joint kinetic estimation with correct kinetics (sanity check)", needs="kinetics"),
        Cell("k100_ie_a0_sensors", "k100_ie_a0", "k100", ("cl_pinn",), "A0", "exact",
             "E3: sensor-value confirmation, one channel dropped and one added", needs="sensors"),
    ]


def read_kinetic_subset(path: Path) -> list[str]:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    names = data.get("names") if isinstance(data, dict) else None
    if not isinstance(names, list) or not names or not all(isinstance(n, str) for n in names):
        raise ValueError('%s: expected {"names": [<kinetic parameter>, ...]}' % path)
    allowed = kinetic_parameter_names(vault())
    unknown = [n for n in names if n not in allowed]
    if unknown or len(set(names)) != len(names):
        raise ValueError("%s: names %s must be distinct members of %s" % (path, names, list(allowed)))
    return list(names)


def read_sensor_confirmation(path: Path) -> tuple[str, str]:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError('%s: expected {"drop": ..., "add": ...}' % path)
    drop, add = data.get("drop"), data.get("add")
    targets = [c.name for c in TARGET_CHANNELS]
    candidates = [c.name for c in CANDIDATE_CHANNELS]
    if drop not in targets:
        raise ValueError("%s: drop %r is not one of the target channels %s" % (path, drop, targets))
    if add not in candidates:
        raise ValueError("%s: add %r is not one of the candidate channels %s" % (path, add, candidates))
    return str(drop), str(add)


def build(
    cell: Cell,
    base: dict[str, Any],
    kinetic_names: list[str] | None = None,
    sensor_choice: tuple[str, str] | None = None,
) -> dict[str, Any]:
    """One regime config as an ordered mapping, ready for yaml.safe_dump."""
    out: dict[str, Any] = {"models": list(cell.models), "noise_levels": list(cell.noise_levels)}
    for key, value in base.items():
        if key in ("models", "noise_levels", "pinn", "lstm"):
            continue
        out[key] = value
    out.update(V11_SETTINGS)
    out["data_dir"] = DATA_DIRS[cell.k]
    out["out_dir"] = "%s/%s" % (PINN_ROOT, cell.cell)
    out["anchor_file"] = (
        None if cell.anchor is None else "%s/%s/%s.npz" % (ANCHOR_ROOT, cell.k, cell.anchor)
    )
    out["influent_mode"] = cell.influent_mode
    if cell.needs == "kinetics":
        if not kinetic_names:
            raise ValueError("%s needs the kinetic subset" % cell.stem)
        out["trainable_kinetics"] = list(kinetic_names)
    if cell.needs == "sensors":
        if sensor_choice is None:
            raise ValueError("%s needs the sensor confirmation choice" % cell.stem)
        drop, add = sensor_choice
        default = [c.name for c in TARGET_CHANNELS]
        out["variants"] = [
            {"suffix": "drop-%s" % drop,
             "overrides": {"target_channels": [n for n in default if n != drop]}},
            {"suffix": "add-%s" % add, "overrides": {"target_channels": default + [add]}},
        ]
    out["pinn"] = base["pinn"]
    out["lstm"] = base["lstm"]
    return out


def render(cell: Cell, config: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "# Cell %s: %s" % (cell.stem, cell.purpose),
        "# python -m scripts.run_all --config configs/regime/%s.yaml --profile full --seed <k> --resume"
        % cell.stem,
        "",
    ]
    return "\n".join(lines) + yaml.safe_dump(config, sort_keys=False)


def expected_files(
    base: dict[str, Any], realistic_k: str, kinetic_path: Path, sensor_path: Path
) -> tuple[dict[str, str], list[str]]:
    """``({file name: text}, [skip messages])`` for the current inputs."""
    kinetic_names = read_kinetic_subset(kinetic_path) if Path(kinetic_path).exists() else None
    sensor_choice = read_sensor_confirmation(sensor_path) if Path(sensor_path).exists() else None
    files: dict[str, str] = {}
    skipped: list[str] = []
    for cell in cells(realistic_k):
        if cell.needs == "kinetics" and kinetic_names is None:
            skipped.append("%s.yaml: %s not found (group G4)" % (cell.stem, kinetic_path))
            continue
        if cell.needs == "sensors" and sensor_choice is None:
            skipped.append("%s.yaml: %s not found (group G4)" % (cell.stem, sensor_path))
            continue
        files[cell.stem + ".yaml"] = render(cell, build(cell, base, kinetic_names, sensor_choice))
    return files, skipped


def generated_on_disk(out_dir: Path) -> list[Path]:
    """Files in ``out_dir`` that carry the generator header (never hand-written ones)."""
    if not out_dir.exists():
        return []
    return sorted(
        p for p in out_dir.glob("*.yaml")
        if p.read_text(encoding="utf-8").splitlines()[:1] == [HEADER]
    )


def dry_run(paths: list[Path], steps: int = 2) -> tuple[list[str], list[str]]:
    """Build and train every run of ``paths`` for ``steps`` CPU steps.

    Returns ``(failures, skipped)``. A run is skipped when its data directory or
    anchor file does not exist yet. Nothing is written outside a temp folder.
    """
    from scripts.run_all import expand
    from src.train.run import Trainer, dataset_path

    failures: list[str] = []
    skipped: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        for path in paths:
            base = yaml.safe_load(path.read_text(encoding="utf-8"))
            for cfg in expand(base, base["models"], base["noise_levels"], "quick"):
                label = "%s/%s" % (path.stem, cfg.run_id)
                needed = [dataset_path(cfg, "dry"), dataset_path(cfg, "constant")]
                if cfg.anchor_file:
                    needed.append(Path(cfg.anchor_file))
                missing = [str(p) for p in needed if not Path(p).exists()]
                if missing:
                    skipped.append("%s: missing %s" % (label, missing))
                    print("SKIP  %s  missing %s" % (label, missing))
                    continue
                cfg = dataclasses.replace(
                    cfg, steps_quick=steps, log_every=1, device="cpu",
                    out_dir=str(Path(tmp) / path.stem),
                )
                try:
                    summary = Trainer(cfg).train()
                except Exception as exc:
                    failures.append("%s: %s: %s" % (label, type(exc).__name__, exc))
                    print("FAIL  %s  %s: %s" % (label, type(exc).__name__, exc))
                    continue
                losses = summary.get("final_losses", {})
                bad = [k for k, v in losses.items() if isinstance(v, float) and not np.isfinite(v)]
                if bad:
                    failures.append("%s: non-finite %s" % (label, bad))
                    print("FAIL  %s  non-finite %s" % (label, bad))
                else:
                    print("OK    %s  total %.4e  anchor %s  influent %s  targets %d"
                          % (label, losses.get("total", float("nan")), summary["anchor"],
                             summary["influent_mode"], len(summary["target_channels"])))
    return failures, skipped


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", default=str(BASE_CONFIG))
    parser.add_argument("--out-dir", default=str(OUT_DIR))
    parser.add_argument("--realistic-k", default="k100", choices=REALISTIC_CHOICES,
                        help="kinetics of the realistic E6 cells; k050 when gate D3 fires")
    parser.add_argument("--kinetic-subset", default=str(KINETIC_SUBSET))
    parser.add_argument("--sensor-confirmation", default=str(SENSOR_CONFIRMATION))
    parser.add_argument("--check", action="store_true", help="compare with disk, write nothing")
    parser.add_argument("--dry-run", action="store_true",
                        help="train every run in --out-dir for 2 CPU steps, write nothing")
    parser.add_argument("--require-all", action="store_true",
                        help="treat skipped files (write/check) or runs (dry run) as failures")
    args = parser.parse_args(argv)
    out_dir = Path(args.out_dir)

    if args.dry_run:
        paths = generated_on_disk(out_dir)
        if not paths:
            print("no generated configs in %s" % out_dir)
            return 1
        failures, skipped = dry_run(paths)
        print("dry run: %d failed, %d skipped" % (len(failures), len(skipped)))
        return 1 if failures or (skipped and args.require_all) else 0

    base = yaml.safe_load(Path(args.base).read_text(encoding="utf-8"))
    files, skipped = expected_files(
        base, args.realistic_k, Path(args.kinetic_subset), Path(args.sensor_confirmation)
    )
    for message in skipped:
        print("SKIPPED %s" % message)
    stale = [p for p in generated_on_disk(out_dir) if p.name not in files]

    if args.check:
        drift = [name for name, text in files.items()
                 if not (out_dir / name).exists()
                 or (out_dir / name).read_text(encoding="utf-8") != text]
        for name in drift:
            print("DRIFT %s" % (out_dir / name))
        for path in stale:
            print("STALE %s" % path)
        ok = not drift and not stale and not (skipped and args.require_all)
        print("check %s: %d files" % ("passed" if ok else "FAILED", len(files)))
        return 0 if ok else 1

    out_dir.mkdir(parents=True, exist_ok=True)
    for path in stale:
        path.unlink()
        print("removed %s" % path)
    for name, text in files.items():
        (out_dir / name).write_text(text, encoding="utf-8")
        print("wrote %s" % (out_dir / name))
    return 1 if (skipped and args.require_all) else 0


if __name__ == "__main__":
    raise SystemExit(main())
