"""Write, run and check the CPU estimator grid of v1.1 (strategic plan E2; group G6).

    python -m scripts.observer_grid write --stage numerics
    python -m scripts.observer_grid contract
    python -m scripts.observer_grid run --stage numerics
    python -m scripts.observer_grid run --stage numerics --family numerics_ieks
    python -m scripts.observer_grid baselines --stage numerics
    python -m scripts.observer_grid write --stage grid          # needs gate_d3.json, observer_numerics.json
    python -m scripts.observer_grid count --stage grid
    python -m scripts.observer_grid run --stage grid            # needs the v1.1.0-prereg tag
    python -m scripts.observer_grid baselines --stage grid
    python -m scripts.observer_grid status --stage grid

One YAML file per cell (schema: src.observers.cell_inputs.validate_cell_config),
consumed by scripts/run_observers.py. The numerics stage runs before the
pre-registration and is read only through filter diagnostics and gate D3. The
grid stage is written before the registration and runs only after the tag.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.v11_plan import (
    ANCHOR_ROOT, BASELINE_ROOT, DATA_DIRS, NUMERICS_BASELINE_ROOT, NUMERICS_OBSERVER_ROOT,
    OBSERVER_CONFIG_DIR, OBSERVER_ROOT, REPO, SIGMA, V11, kinetic_names, log_deviation,
    primary_smoother, realistic_k, registration_state, sigma_tag,
)
from src.observers.cell_inputs import (
    DEFAULT_TARGETS, expected_run_dirs, load_cell_config, validate_cell_config,
)
from src.observers.ekf import Q_GRID

K_TAGS = ("k000", "k025", "k050", "k075", "k100")
INFLUENT = {"ie": "exact", "ic": "composite", "ib": "composite_biased"}
ANCHORS = {"a0": "A0", "as": "As", "al1": "Al1", "al2": "Al2"}
FULL = ("ekf", "eks", "ekf_aug", "eks_aug", "ekf_online")
PAIR = ("ekf", "eks")
BOTH_Q = ("tuned", "frozen")
TUNED = ("tuned",)
NOISE_SWEEP = (0.0, 0.05, 0.10, 0.15)
R_FLOOR = 0.01
RAS_FILTER_WINDOW = 4
THETA_PRIOR_SD = 0.693
Q_THETA = 1e-3
BASELINE_ROWS = ("persistence", "ode_openloop_reduced", "ode_openloop_full")
FROZEN_Q_SOURCE = "%s/k000_ie_a0/ekf_sigma0p10/summary.json" % OBSERVER_ROOT
CONTRACT_ROOT = "results/v11/_contract"
RAND_ROOT = Path("results/raw_rand")
HEADER = "# Generated by scripts/observer_grid.py (%s stage). Do not edit by hand.\n"
STAGE_DIRS = {"numerics": ("numerics", "numerics_ieks"), "grid": ("grid",)}
SINGLE_THREAD_ENV = {"OMP_NUM_THREADS": "1", "MKL_NUM_THREADS": "1", "OPENBLAS_NUM_THREADS": "1"}
BYTES_PER_WORKER = int(0.5 * 2**30)
RESERVED_BYTES = int(3.0 * 2**30)
MAX_WORKERS = 12
CONTRACT_KEYS = ("run_id", "model", "arch", "curriculum", "noise", "seed", "profile", "steps",
                 "train_seconds", "n_parameters", "train_end_day", "holdout_days",
                 "finite", "nis_mean", "n_measured", "selected_q")


def cell(cell_id: str, data_dir: str, anchor_tag: str, influent: str, anchor: str, out_root: str,
         estimators: Sequence[str], q_modes: Sequence[str], sigmas: Iterable[float] = (SIGMA,),
         realisations: Iterable[int] = (0,), augment: Sequence[str] = (),
         ras_input: str = "filtered", channels: str | Sequence[str] = "default") -> dict[str, Any]:
    uses_aug = any(e.endswith("_aug") for e in estimators)
    spec = {
        "cell": cell_id,
        "out_dir": "%s/%s" % (out_root, cell_id),
        "data_dir": data_dir,
        "anchor_file": "%s/%s/%s.npz" % (ANCHOR_ROOT, anchor_tag, ANCHORS[anchor]),
        "influent_mode": INFLUENT[influent],
        "ras_filter_window": RAS_FILTER_WINDOW,
        "ras_input": ras_input,
        "channels": channels if isinstance(channels, str) else list(channels),
        "sigmas": [float(s) for s in sigmas],
        "realisations": [int(r) for r in realisations],
        "estimators": list(estimators),
        "q_mode": list(q_modes),
        "q_grid": list(Q_GRID),
        "r_floor": R_FLOOR,
        "tune_window_days": [0.0, 12.0],
        "augment": list(augment) if uses_aug else [],
        "theta_prior_sd": THETA_PRIOR_SD,
        "q_theta": Q_THETA,
        "frozen_q_from": FROZEN_Q_SOURCE if "frozen" in q_modes else None,
    }
    return validate_cell_config(spec, source=cell_id)


def claim_cells(realistic: str) -> tuple[str, ...]:
    k = realistic
    return ("k000_ie_a0", "k000_ic_a0", "k050_ie_a0", "k100_ie_a0", "%s_ic_a0" % k, "%s_ic_as" % k, "%s_ic_al1" % k)


def noise_cells(realistic: str) -> tuple[str, ...]:
    cells = ("k000_ie_a0", "k100_ie_a0", "k100_ic_as", "k100_ic_al1")
    if realistic == "k050":
        cells += ("k050_ic_as", "k050_ic_al1")
    return cells


def _main_cells():
    for k in K_TAGS:
        for i in INFLUENT:
            for a in ANCHORS:
                yield "%s_%s_%s" % (k, i, a), k, i, a


def numerics_files() -> dict[str, dict]:
    files: dict[str, dict] = {}
    for cid, k, i, a in _main_cells():
        files["numerics/" + cid] = cell(cid, DATA_DIRS[k], k, i, a, NUMERICS_OBSERVER_ROOT, PAIR, TUNED)
        files["numerics_ieks/" + cid] = cell(cid, DATA_DIRS[k], k, i, a, NUMERICS_OBSERVER_ROOT, ("ieks",), TUNED)
    return files


def main_files(realistic: str, augment: Sequence[str], smoother: str) -> dict[str, dict]:
    files: dict[str, dict] = {}
    claims, noisy = claim_cells(realistic), noise_cells(realistic)
    for cid, k, i, a in _main_cells():
        est = FULL + (("ieks",) if smoother == "ieks" or cid in claims else ())
        sig = NOISE_SWEEP if cid in noisy else (SIGMA,)
        args = (cid, DATA_DIRS[k], k, i, a, OBSERVER_ROOT, est)
        if cid == "k000_ie_a0":
            files["grid/main/" + cid] = cell(*args, TUNED, sigmas=(SIGMA,), augment=augment)
            files["grid/main/%s__noise" % cid] = cell(*args, TUNED, sigmas=[s for s in sig if s != SIGMA], augment=augment)
            files["grid/main/%s__frozen" % cid] = cell(*args, ("frozen",), sigmas=sig, augment=augment)
        else:
            files["grid/main/" + cid] = cell(*args, BOTH_Q, sigmas=sig, augment=augment)
    return files


def realisation_files() -> dict[str, dict]:
    return {
        "grid/realisations/%s__r" % cid: cell(cid, DATA_DIRS[k], k, i, a, OBSERVER_ROOT, PAIR, TUNED,
                                              realisations=range(1, 10))
        for cid, k, i, a in (("k000_ie_a0", "k000", "ie", "a0"), ("k100_ic_as", "k100", "ic", "as"))
    }


def m0prime_files(augment: Sequence[str]) -> dict[str, dict]:
    return {
        "grid/m0prime/k000off_ie_%s" % a: cell("k000off_ie_%s" % a, DATA_DIRS["k000_off"], "k000_off", "ie", a,
                                                OBSERVER_ROOT, FULL, BOTH_Q, augment=augment)
        for a in ("a0", "as", "al1")
    }


def random_files(rands: Sequence[str], augment: Sequence[str]) -> dict[str, dict]:
    return {
        "grid/random/rand%s_ie_a0" % r: cell("rand%s_ie_a0" % r, (RAND_ROOT / r).as_posix(), "rand/%s" % r,
                                              "ie", "a0", OBSERVER_ROOT, ("eks", "eks_aug"), TUNED, augment=augment)
        for r in rands
    }


def sigma_log_files() -> dict[str, dict]:
    return {
        "grid/sigma_log/k100_ic_%s_sl%s" % (a, tag): cell("k100_ic_%s_sl%s" % (a, tag), DATA_DIRS["k100"],
                                                          "k100_slog%s" % tag, "ic", a, OBSERVER_ROOT, PAIR, TUNED)
        for a in ("as", "al1") for tag in ("04", "08")
    }


LAB_REALISATIONS = tuple(range(1, 10))


def lab_files(realistic: str) -> dict[str, dict]:
    """Nine extra lab-panel noise seeds for Al1 and Al2 in the realistic cell (added 2026-09-24).

    Anchors in results/v11/anchors/<k>_lab/rXX (make_anchors --lab-seed 20260923 + XX), with
    <k> the realistic kinetics of gate D3. Reported as a spread around the registered
    seed-20260923 cells, never pooled.
    """
    return {
        "grid/lab/%s_ic_%s_lab%02d" % (realistic, a, r): cell(
            "%s_ic_%s_lab%02d" % (realistic, a, r), DATA_DIRS[realistic], "%s_lab/r%02d" % (realistic, r),
            "ic", a, OBSERVER_ROOT, PAIR, TUNED)
        for a in ("al1", "al2") for r in LAB_REALISATIONS
    }


def settler_files() -> dict[str, dict]:
    return {"grid/settler/k100_ie_a0_ideal": cell("k100_ie_a0_ideal", DATA_DIRS["k100"], "k100", "ie", "a0",
                                                  OBSERVER_ROOT, PAIR, TUNED, ras_input="ideal_settler")}


def sensor_subsets(targets: Sequence[str], candidates: Sequence[str]) -> dict[str, list[str]]:
    subsets = {"drop-%s" % c: [t for t in targets if t != c] for c in targets}
    subsets["drop-DO"] = [t for t in targets if not t.startswith("S_O_")]
    subsets["drop-Nanalysers"] = [t for t in targets if not t.startswith(("S_NH_", "S_NO_"))]
    for c in candidates:
        subsets["add-%s" % c] = [*targets, c]
    return subsets


def sensor_files(candidates: Sequence[str]) -> dict[str, dict]:
    return {
        "grid/sensors/k100_ie_a0_%s" % name: cell("k100_ie_a0_%s" % name, DATA_DIRS["k100"], "k100", "ie", "a0",
                                                  OBSERVER_ROOT, PAIR, TUNED, channels=chans)
        for name, chans in sensor_subsets(DEFAULT_TARGETS, candidates).items()
    }


def grid(stage: str, realistic: str | None = None, rands: Sequence[str] = (), candidates: Sequence[str] = (),
         augment: Sequence[str] = (), smoother: str = "eks") -> dict[str, dict]:
    if stage == "numerics":
        return numerics_files()
    if stage != "grid":
        raise ValueError("stage must be 'numerics' or 'grid', got %r" % stage)
    if realistic not in ("k100", "k050"):
        raise ValueError("realistic must be 'k100' or 'k050', got %r" % realistic)
    if smoother not in ("eks", "ieks"):
        raise ValueError("smoother must be 'eks' or 'ieks', got %r" % smoother)
    files: dict[str, dict] = {}
    files.update(main_files(realistic, augment, smoother))
    files.update(realisation_files())
    files.update(m0prime_files(augment))
    files.update(random_files(rands, augment))
    files.update(sigma_log_files())
    files.update(lab_files(realistic))
    files.update(settler_files())
    files.update(sensor_files(candidates))
    return files


def candidate_names() -> list[str]:
    from src.data.sensors import CANDIDATE_CHANNELS

    return [c.name for c in CANDIDATE_CHANNELS]


def rand_names(root: Path = RAND_ROOT) -> list[str]:
    names = [p.name for p in (REPO / root).iterdir() if p.is_dir()]
    return sorted(names, key=lambda s: (len(s), s))


def build(stage: str) -> dict[str, dict]:
    if stage == "numerics":
        return grid("numerics")
    return grid("grid", realistic_k(), rand_names(), candidate_names(), kinetic_names(), primary_smoother())


def write(stage: str, root: Path = OBSERVER_CONFIG_DIR) -> list[Path]:
    files = build(stage)
    needed = sorted({p for c in files.values() for p in (c["data_dir"], c["anchor_file"])})
    missing = [p for p in needed if not (REPO / p).exists()]
    if missing:
        raise FileNotFoundError("inputs missing for the %s stage (%d): %s" % (stage, len(missing), ", ".join(missing[:10])))
    for sub in STAGE_DIRS[stage]:
        for old in (REPO / root / sub).rglob("*.yaml"):
            old.unlink()
    written = []
    for key, cfg in sorted(files.items()):
        path = REPO / root / (key + ".yaml")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(HEADER % stage + yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
        written.append(path)
    return written


def load_stage(stage: str, root: Path = OBSERVER_CONFIG_DIR) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for sub in STAGE_DIRS[stage]:
        for path in sorted((REPO / root / sub).rglob("*.yaml")):
            out[path.relative_to(REPO / root).with_suffix("").as_posix()] = load_cell_config(path)
    if not out:
        raise FileNotFoundError("no %s-stage YAML under %s; run 'write --stage %s' first" % (stage, root, stage))
    return out


def count(stage: str) -> int:
    fams: dict[str, list] = {}
    for key, cfg in load_stage(stage).items():
        fam = key.split("/")[1] if stage == "grid" else key.split("/")[0]
        entry = fams.setdefault(fam, [0, set(), 0])
        entry[0] += 1
        entry[1].add(cfg["cell"])
        entry[2] += len(expected_run_dirs(cfg))
    for fam, (n, cells, runs) in sorted(fams.items()):
        print("%-14s %4d files %4d cells %5d estimator runs" % (fam, n, len(cells), runs))
    print("%-14s %4d files            %5d estimator runs"
          % ("total", sum(e[0] for e in fams.values()), sum(e[2] for e in fams.values())))
    return 0


def available_bytes() -> int | None:
    if sys.platform == "win32":
        import ctypes

        class MemoryStatusEx(ctypes.Structure):
            _fields_ = [("dwLength", ctypes.c_ulong), ("dwMemoryLoad", ctypes.c_ulong),
                        ("ullTotalPhys", ctypes.c_ulonglong), ("ullAvailPhys", ctypes.c_ulonglong),
                        ("ullTotalPageFile", ctypes.c_ulonglong), ("ullAvailPageFile", ctypes.c_ulonglong),
                        ("ullTotalVirtual", ctypes.c_ulonglong), ("ullAvailVirtual", ctypes.c_ulonglong),
                        ("ullAvailExtendedVirtual", ctypes.c_ulonglong)]

        stat = MemoryStatusEx()
        stat.dwLength = ctypes.sizeof(MemoryStatusEx)
        if not ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(stat)):
            return None
        return int(stat.ullAvailPhys)
    try:
        return int(os.sysconf("SC_AVPHYS_PAGES") * os.sysconf("SC_PAGE_SIZE"))
    except (ValueError, OSError, AttributeError):
        return None


def default_workers() -> int:
    avail = available_bytes()
    if avail is None:
        return 8
    return max(1, min(MAX_WORKERS, int((avail - RESERVED_BYTES) // BYTES_PER_WORKER)))


def _registered(allow_drift: str | None) -> bool:
    state, detail = registration_state()
    if state == "ok":
        return True
    if state == "drift" and allow_drift:
        log_deviation(allow_drift, detail, "observer_grid")
        return True
    hint = "" if state == "no_tag" else "; pass --allow-drift REASON to proceed and log it"
    print("REFUSED: %s. The final grid runs only after the pre-registration%s." % (detail, hint))
    return False


def _run_one(key: str, inner_workers: int = 1) -> int:
    path = OBSERVER_CONFIG_DIR / (key + ".yaml")
    cfg = load_cell_config(REPO / path)
    out = REPO / cfg["out_dir"]
    out.mkdir(parents=True, exist_ok=True)
    with open(out / ("run_observers_%s.log" % Path(key).name), "a", encoding="utf-8") as log:
        return subprocess.run(
            [sys.executable, "-m", "scripts.run_observers", "--config", path.as_posix(),
             "--workers", str(inner_workers), "--resume"],
            cwd=REPO, stdout=log, stderr=subprocess.STDOUT, env={**os.environ, **SINGLE_THREAD_ENV},
        ).returncode


def _run_files(keys: list[str], workers: int, inner_workers: int = 1) -> int:
    print("run_observers: %d files on %d workers" % (len(keys), workers), flush=True)
    with ThreadPoolExecutor(max_workers=max(1, workers)) as pool:
        codes = dict(zip(keys, pool.map(lambda k: _run_one(k, inner_workers), keys)))
    failed = sorted(k for k, c in codes.items() if c != 0)
    for key in failed:
        print("  EXIT %d  %s (see run_observers_*.log in its out_dir)" % (codes[key], key))
    return 1 if failed else 0


def run(stage: str, family: str | None = None, workers: int | None = None, allow_drift: str | None = None) -> int:
    if stage == "grid" and not _registered(allow_drift):
        return 3
    files = load_stage(stage)
    workers = workers or default_workers()
    if stage == "numerics":
        fam = family or "numerics"
        return _run_files([k for k in files if k.startswith(fam + "/")], workers)
    first = "grid/main/k000_ie_a0"
    code = _run_files([first], 1, inner_workers=6)
    if not (REPO / FROZEN_Q_SOURCE).exists():
        print("STOP: %s was not written; the frozen-q runs cannot start." % FROZEN_Q_SOURCE)
        return 2
    return max(code, _run_files([k for k in files if k != first], workers))


def _baseline_argv(cfg: dict, root: str, rows: Sequence[str]) -> list[str]:
    return ["--data-dir", cfg["data_dir"], "--out", "%s/%s" % (root, cfg["cell"]),
            "--anchor-file", cfg["anchor_file"], "--rows", *rows,
            "--ras-filter-window", str(cfg["ras_filter_window"]), "--influent-mode", cfg["influent_mode"]]


def baseline_jobs(stage: str, files: dict[str, dict]) -> list[list[str]]:
    if stage == "numerics":
        return [_baseline_argv(files["numerics/k100_ic_as"], NUMERICS_BASELINE_ROOT, ("persistence",))]
    seen: dict[str, list[str]] = {}
    for key, cfg in sorted(files.items()):
        family = key.split("/")[1]
        if family in ("main", "m0prime", "sigma_log", "random") and cfg["cell"] not in seen:
            argv = _baseline_argv(cfg, BASELINE_ROOT, BASELINE_ROWS)
            seen[cfg["cell"]] = argv + ["--sigmas", "%.2f" % SIGMA] if family == "random" else argv
    return list(seen.values())


def _baseline_dirs(argv: list[str]) -> list[Path]:
    out = Path(argv[argv.index("--out") + 1])
    rows = argv[argv.index("--rows") + 1: argv.index("--ras-filter-window")]
    return [out / ("%s_sigma%s" % (row, sigma_tag(SIGMA))) for row in rows]


def run_baselines(stage: str, workers: int, allow_drift: str | None = None) -> int:
    if stage == "grid" and not _registered(allow_drift):
        return 3
    todo = [a for a in baseline_jobs(stage, load_stage(stage))
            if not all((REPO / d / "summary.json").exists() for d in _baseline_dirs(a))]
    print("make_baselines: %d invocations pending" % len(todo), flush=True)

    def one(argv: list[str]) -> int:
        out = REPO / argv[argv.index("--out") + 1]
        out.mkdir(parents=True, exist_ok=True)
        with open(out / "make_baselines.log", "a", encoding="utf-8") as log:
            return subprocess.run([sys.executable, "-m", "scripts.make_baselines", *argv], cwd=REPO,
                                  stdout=log, stderr=subprocess.STDOUT,
                                  env={**os.environ, **SINGLE_THREAD_ENV}).returncode

    with ThreadPoolExecutor(max_workers=max(1, workers)) as pool:
        codes = list(pool.map(one, todo))
    failed = [a[a.index("--out") + 1] for a, c in zip(todo, codes) if c != 0]
    for path in failed:
        print("  FAILED make_baselines --out %s (see make_baselines.log)" % path)
    return 1 if failed else 0


def classify_run_dir(run_dir: Path) -> str:
    if (run_dir / "summary.json").exists() and (run_dir / "predictions.npz").exists():
        return "ok"
    return "error" if (run_dir / "error.txt").exists() else "missing"


def numerics_reproduced(files: dict[str, dict]) -> dict[str, int]:
    """Final-grid tuned EKF/EKS at sigma 0.10 must equal the numerics pass bit for bit."""
    same = differ = 0
    for key, cfg in files.items():
        if not key.startswith("grid/main/") or "__" in key:
            continue
        for est in PAIR:
            final = REPO / cfg["out_dir"] / ("%s_sigma0p10" % est) / "predictions.npz"
            pre = REPO / NUMERICS_OBSERVER_ROOT / cfg["cell"] / ("%s_sigma0p10" % est) / "predictions.npz"
            if final.exists() and pre.exists():
                with np.load(final) as a, np.load(pre) as b:
                    if np.array_equal(a["train"], b["train"]):
                        same += 1
                    else:
                        differ += 1
    return {"identical": same, "different": differ}


def status(stage: str) -> int:
    files = load_stage(stage)
    runs = {d.as_posix(): classify_run_dir(REPO / d) for c in files.values() for d in expected_run_dirs(c)}
    base = {d.as_posix(): classify_run_dir(REPO / d) for a in baseline_jobs(stage, files) for d in _baseline_dirs(a)}

    def counts(m: dict[str, str]) -> dict[str, int]:
        return {s: sum(1 for v in m.values() if v == s) for s in ("ok", "error", "missing")}

    report: dict[str, Any] = {"stage": stage, "estimator_runs": counts(runs), "baseline_runs": counts(base),
                              "errors": sorted(k for k, v in {**runs, **base}.items() if v == "error"),
                              "missing": sorted(k for k, v in {**runs, **base}.items() if v == "missing")}
    if stage == "grid":
        report["numerics_reproduced"] = numerics_reproduced(files)
    out = REPO / V11 / ("observer_status_%s.json" % stage)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print("estimator runs %s | baseline runs %s%s -> %s" % (
        report["estimator_runs"], report["baseline_runs"],
        " | numerics reproduced %s" % report["numerics_reproduced"] if stage == "grid" else "",
        out.relative_to(REPO).as_posix()))
    return 0 if not report["missing"] else 1


def check_contract_runs(cfg: dict) -> list[str]:
    problems: list[str] = []
    with np.load(REPO / DATA_DIRS["k000"] / "obs_dry_sigma0p10.npz") as data:
        t = np.asarray(data["t"])
    shapes = {"train": (int(np.sum(t <= 12.0 + 1e-9)), 5, 14), "holdout": (int(np.sum(t >= 12.0 - 1e-9)), 5, 14)}
    for run_dir in expected_run_dirs(cfg):
        d = REPO / run_dir
        if not (d / "summary.json").exists():
            problems.append("%s: no summary.json" % run_dir.as_posix())
            continue
        s = json.loads((d / "summary.json").read_text(encoding="utf-8"))
        missing = [k for k in CONTRACT_KEYS if k not in s]
        if missing:
            problems.append("%s: summary lacks %s" % (run_dir.as_posix(), missing))
        if s.get("arch") != "observer" or s.get("model") != run_dir.name.split("_sigma")[0]:
            problems.append("%s: arch/model %r/%r" % (run_dir.as_posix(), s.get("arch"), s.get("model")))
        if run_dir.name.startswith(("ekf_aug", "eks_aug")) and sorted(s.get("learned_multipliers") or {}) != sorted(cfg["augment"]):
            problems.append("%s: learned_multipliers %r" % (run_dir.as_posix(), s.get("learned_multipliers")))
        with np.load(d / "predictions.npz") as p:
            for key, shape in shapes.items():
                if key not in p.files or p[key].shape != shape or not np.isfinite(p[key]).all():
                    problems.append("%s: predictions[%r] missing, wrong shape or non-finite" % (run_dir.as_posix(), key))
    return problems


def contract(inner_workers: int = 1) -> int:
    """One K0-Ie-A0 cell with a single q value, through the real run_observers and collect_runs."""
    from src.eval.report import collect_runs

    root = Path(CONTRACT_ROOT)
    tuned = cell("k000_ie_a0", DATA_DIRS["k000"], "k000", "ie", "a0", root.as_posix(), FULL + ("ieks",), TUNED,
                 augment=kinetic_names())
    tuned["q_grid"] = [0.03]
    frozen = dict(tuned, estimators=["eks"], q_mode=["frozen"], augment=[],
                  frozen_q_from=(root / "k000_ie_a0" / "ekf_sigma0p10" / "summary.json").as_posix())
    problems: list[str] = []
    for name, raw in (("tuned", tuned), ("frozen", frozen)):
        cfg = validate_cell_config(raw, source="contract_" + name)
        path = REPO / root / "configs" / ("%s.yaml" % name)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(HEADER % "contract" + yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
        code = subprocess.run([sys.executable, "-m", "scripts.run_observers", "--config", path.as_posix(),
                               "--workers", str(inner_workers), "--resume"], cwd=REPO,
                              env={**os.environ, **SINGLE_THREAD_ENV}).returncode
        if code != 0:
            problems.append("run_observers exit %d on %s" % (code, path.name))
        problems.extend(check_contract_runs(cfg))
    cell_dir = REPO / root / "k000_ie_a0"
    tuned_q = json.loads((cell_dir / "ekf_sigma0p10" / "summary.json").read_text(encoding="utf-8")).get("selected_q")
    frozen_path = cell_dir / "eks_frozenq_sigma0p10" / "summary.json"
    if frozen_path.exists() and json.loads(frozen_path.read_text(encoding="utf-8")).get("selected_q") != tuned_q:
        problems.append("frozen run did not reuse the tuned q %r" % (tuned_q,))
    rows = collect_runs(cell_dir, REPO / DATA_DIRS["k000"])
    if len({r["run_id"] for r in rows}) != 7:
        problems.append("collect_runs scored %d runs, expected 7" % len({r["run_id"] for r in rows}))
    report = {"passed": not problems, "problems": problems}
    (REPO / root / "contract_report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print("CONTRACT %s%s" % ("PASS" if not problems else "FAIL", "" if not problems else ":\n  " + "\n  ".join(problems)))
    return 0 if not problems else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["write", "count", "run", "baselines", "status", "contract"])
    parser.add_argument("--stage", choices=["numerics", "grid"], default=None)
    parser.add_argument("--family", default=None, help="numerics stage: 'numerics' (default) or 'numerics_ieks'")
    parser.add_argument("--workers", type=int, default=None)
    parser.add_argument("--allow-drift", default=None, metavar="REASON")
    args = parser.parse_args(argv)
    if args.command != "contract" and args.stage is None:
        parser.error("--stage is required for %s" % args.command)
    if args.command == "write":
        written = write(args.stage)
        print("wrote %d YAML files under %s" % (len(written), OBSERVER_CONFIG_DIR.as_posix()))
        return 0
    if args.command == "count":
        return count(args.stage)
    if args.command == "run":
        return run(args.stage, args.family, args.workers, args.allow_drift)
    if args.command == "baselines":
        return run_baselines(args.stage, args.workers or default_workers(), args.allow_drift)
    if args.command == "status":
        return status(args.stage)
    return contract(args.workers or 1)


if __name__ == "__main__":
    raise SystemExit(main())
